import type { Employee } from "@/lib/types/employee";

export const employees: Employee[] = [
  {
    id: 1,
    name: "Arletta",
    role: "Founder",
    department: "Executive Leadership",
    email: null,
    phone: null,
    status: "Active",
    loginStatus: "Not Invited",
    initials: "A",
  },
  {
    id: 2,
    name: "Kayla Arnold",
    role: "Chief Operating Officer",
    department: "Executive Leadership",
    email: "kayla.arnold91@gmail.com",
    phone: "(404) 293-2008",
    status: "Active",
    loginStatus: "Active",
    initials: "KA",
  },
  {
    id: 3,
    name: "Trent",
    role: "Trading Coach",
    department: "Coaching",
    email: null,
    phone: null,
    status: "Active",
    loginStatus: "Not Invited",
    initials: "T",
  },
  {
    id: 4,
    name: "Tammy",
    role: "Coach",
    department: "Coaching",
    email: null,
    phone: null,
    status: "Active",
    loginStatus: "Not Invited",
    initials: "T",
  },
  {
    id: 5,
    name: "Anita",
    role: "Community Director",
    department: "Community",
    email: null,
    phone: null,
    status: "Active",
    loginStatus: "Not Invited",
    initials: "A",
  },
  {
    id: 6,
    name: "Crystal",
    role: "Technology Coordinator",
    department: "Technology",
    email: null,
    phone: null,
    status: "Active",
    loginStatus: "Not Invited",
    initials: "C",
  },
  {
    id: 7,
    name: "Karen",
    role: "Hospitality Coordinator",
    department: "Hospitality",
    email: null,
    phone: null,
    status: "Active",
    loginStatus: "Not Invited",
    initials: "K",
  },
  {
    id: 8,
    name: "Blair",
    role: "Office Coordinator",
    department: "Office Operations",
    email: null,
    phone: null,
    status: "Active",
    loginStatus: "Not Invited",
    initials: "B",
  },
  {
    id: 9,
    name: "Lisa",
    role: "Instructional Coordinator",
    department: "Instruction",
    email: null,
    phone: null,
    status: "Active",
    loginStatus: "Not Invited",
    initials: "L",
  },
  {
    id: 10,
    name: "Ruby",
    role: "Administrative Coordinator",
    department: "Administration",
    email: null,
    phone: null,
    status: "Active",
    loginStatus: "Not Invited",
    initials: "R",
  },
];