import type { PeerCoach } from "@/lib/types/peer-coach";

export const peerCoaches: PeerCoach[] = [
  {
    id: 1,
    name: "Kyhauna Thomas",
    phone: "803-290-3799",
    role: "Peer Coach",
    meetingStatus: "Attended",
    comments: "",
  },
  {
    id: 2,
    name: "Felicia West",
    phone: "570-972-9263",
    role: "Peer Coach",
    meetingStatus: "Attended",
    comments: "",
  },
  {
    id: 3,
    name: "Stephanie Stephens",
    phone: "513-461-4374",
    role: "Peer Coach",
    meetingStatus: "Attended",
    comments: "",
  },
  {
    id: 4,
    name: "Kasha Graves",
    phone: "678-438-6934",
    role: "Peer Coach",
    meetingStatus: "Attended",
    comments: "",
  },
  {
    id: 5,
    name: "LaRonda Moore",
    phone: "702-528-3807",
    role: "Peer Coach",
    meetingStatus: "Did Not Attend",
    comments: "",
  },
  {
    id: 6,
    name: "Raushanah Muhammad",
    phone: "334-379-6069",
    role: "Peer Coach",
    meetingStatus: "Attended",
    comments: "",
  },
  {
    id: 7,
    name: "Ginneh Ivery",
    phone: "330-330-1050",
    role: "Peer Coach",
    meetingStatus: "Attended",
    comments: "",
  },
  {
    id: 8,
    name: "Tracy Miller",
    phone: "919-210-7057",
    role: "Peer Coach",
    meetingStatus: "Attended",
    comments: "",
  },
  {
    id: 9,
    name: "Shante Jenkins",
    phone: "407-721-6520",
    role: "Peer Coach",
    meetingStatus: "Attended",
    comments: "",
  },
  {
    id: 10,
    name: "Chase Slaughter",
    phone: "601-416-7278",
    role: "Peer Coach",
    meetingStatus: "Attended",
    comments: "",
  },
  {
    id: 11,
    name: "Robyn Walker",
    phone: "240-286-8675",
    role: "Peer Coach",
    meetingStatus: "Attended",
    comments: "",
  },
  {
    id: 12,
    name: "Tanya Johnson",
    phone: "732-735-8865",
    role: "Peer Coach",
    meetingStatus: "Attended",
    comments: "",
  },
  {
    id: 13,
    name: "Nicole AMG",
    phone: "786-709-5971",
    role: "Peer Coach",
    meetingStatus: "Attended",
    comments: "",
  },
  {
    id: 14,
    name: "Tiffany J",
    phone: "281-705-8422",
    role: "Accountability Coach",
    meetingStatus: "Did Not Attend",
    comments: "Accountability coach",
  },
  {
    id: 15,
    name: "Melissa B",
    phone: "404-556-0685",
    role: "Peer Coach",
    meetingStatus: "Did Not Attend",
    comments: "",
  },
  {
    id: 16,
    name: "La-Zarus Jackson",
    phone: "334-685-2968",
    role: "Peer Coach",
    meetingStatus: "Did Not Attend",
    comments: "",
  },
  {
    id: 17,
    name: "Patrice Terry",
    phone: "404-514-4153",
    role: "Peer Coach",
    meetingStatus: "Did Not Attend",
    comments: "",
  },
  {
    id: 18,
    name: "Tonya S",
    phone: "",
    role: "Accountability Coach",
    meetingStatus: "Did Not Attend",
    comments: "Accountability coach",
  },
  {
    id: 19,
    name: "Beverly Davis",
    phone: "843-496-8269",
    role: "Peer Coach",
    meetingStatus: "Attended",
    comments: "",
  },
  {
    id: 20,
    name: "Jas Alexander",
    phone: "678-964-3088",
    role: "Peer Coach",
    meetingStatus: "Attended",
    comments: "",
  },
  {
    id: 21,
    name: "Karen Ficklin",
    phone: "678-522-5664",
    role: "Peer Coach",
    meetingStatus: "Did Not Attend",
    comments: "",
  },
  {
    id: 22,
    name: "Lisa Spriggins",
    phone: "682-401-7725",
    role: "Peer Coach",
    meetingStatus: "Attended",
    comments: "",
  },
  {
    id: 23,
    name: "Winnie Rush",
    phone: "803-955-6442",
    role: "Peer Coach",
    meetingStatus: "Attended",
    comments: "",
  },
  {
    id: 24,
    name: "Fletcher Mallard",
    phone: "256-515-1267",
    role: "Peer Coach",
    meetingStatus: "Did Not Attend",
    comments: "",
  },
  {
    id: 25,
    name: "Velvet Street",
    phone: "585-694-2485",
    role: "Peer Coach",
    meetingStatus: "Attended",
    comments: "",
  },
  {
    id: 26,
    name: "Tammika Fortney-Reed",
    phone: "404-992-5565",
    role: "Peer Coach",
    meetingStatus: "Attended",
    comments: "",
  },
  {
    id: 27,
    name: "Sasha Gayle-Foster",
    phone: "754-816-0245",
    role: "Peer Coach",
    meetingStatus: "Attended",
    comments: "",
  },
  {
    id: 28,
    name: "Shaundrea Thomas",
    phone: "973-769-4436",
    role: "Peer Coach",
    meetingStatus: "Attended",
    comments: "",
  },
  {
    id: 29,
    name: "Juanita Green",
    phone: "843-817-7979",
    role: "Peer Coach",
    meetingStatus: "Attended",
    comments: "",
  },
  {
    id: 30,
    name: "Tysheen Daniels",
    phone: "631-307-8151",
    role: "Peer Coach",
    meetingStatus: "Did Not Attend",
    comments: "",
  },
  {
    id: 31,
    name: "Blair Daniels",
    phone: "813-451-8242",
    role: "Peer Coach",
    meetingStatus: "Attended",
    comments: "",
  },
  {
    id: 32,
    name: "Robert Brooks",
    phone: "561-319-8944",
    role: "Peer Coach",
    meetingStatus: "Did Not Attend",
    comments: "",
  },
  {
    id: 33,
    name: "Alfred Shepherd",
    phone: "954-854-9019",
    role: "Peer Coach",
    meetingStatus: "Attended",
    comments: "",
  },
  {
    id: 34,
    name: "Aretha Williams",
    phone: "412-498-8113",
    role: "Peer Coach",
    meetingStatus: "Attended",
    comments: "",
  },
  {
    id: 35,
    name: "DeAna Rentie",
    phone: "619-227-0168",
    role: "Peer Coach",
    meetingStatus: "Attended",
    comments: "",
  },
  {
    id: 36,
    name: "Elizabeth Njoroge",
    phone: "682-298-7471",
    role: "Peer Coach",
    meetingStatus: "Attended",
    comments: "",
  },
  {
    id: 37,
    name: "Engrid Albritton",
    phone: "470-382-8117",
    role: "Peer Coach",
    meetingStatus: "Attended",
    comments: "",
  },
  {
    id: 38,
    name: "Jaya Carter",
    phone: "404-775-8885",
    role: "Peer Coach",
    meetingStatus: "Attended",
    comments: "",
  },
  {
    id: 39,
    name: "LaShawne Brown",
    phone: "",
    role: "Peer Coach",
    meetingStatus: "Attended",
    comments: "",
  },
  {
    id: 40,
    name: "Linda DuBose",
    phone: "917-270-0250",
    role: "Peer Coach",
    meetingStatus: "Attended",
    comments: "",
  },
  {
    id: 41,
    name: "Nerissa Thompson",
    phone: "",
    role: "Peer Coach",
    meetingStatus: "Attended",
    comments: "",
  },
  {
    id: 42,
    name: "Takita Edwards",
    phone: "770-856-5587",
    role: "Peer Coach",
    meetingStatus: "Attended",
    comments: "",
  },
  {
    id: 43,
    name: "Coach Tammy",
    phone: "601-942-6697",
    role: "Accountability Coach",
    meetingStatus: "Attended",
    comments: "Accountability coach",
  },
  {
    id: 44,
    name: "Amirah Elamin",
    phone: "404-379-2408",
    role: "Peer Coach",
    meetingStatus: "Attended",
    comments: "",
  },
];